import { NextResponse } from 'next/server';
import { PutObjectCommand } from '@aws-sdk/client-s3';
import { r2, r2Configured } from '@/lib/r2';
import { verifyIdToken } from '@/lib/verifyAuth';

// Object keys are always generated by our own code (campaignId/influencerId
// are Firestore auto-IDs, plus a crypto.randomUUID() filename) — this just
// guards against a tampered client sending a path outside that shape.
const SAFE_PATH = /^screenshots\/(profiles|conversations)\/[\w-]+(\/[\w-]+)*\.jpg$/;

export async function POST(req: Request) {
  const uid = await verifyIdToken(req);
  if (!uid) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  if (!r2Configured) {
    return NextResponse.json({ error: 'Screenshot storage is not configured on the server.' }, { status: 503 });
  }

  const { imageBase64, path } = await req.json();
  if (!imageBase64 || !path || !SAFE_PATH.test(path)) {
    return NextResponse.json({ error: 'Invalid upload request.' }, { status: 400 });
  }

  try {
    await r2.send(
      new PutObjectCommand({
        Bucket: process.env.R2_BUCKET_NAME,
        Key: path,
        Body: Buffer.from(imageBase64, 'base64'),
        ContentType: 'image/jpeg',
      }),
    );
    const url = `${process.env.R2_PUBLIC_URL!.replace(/\/$/, '')}/${path}`;
    return NextResponse.json({ url });
  } catch (err) {
    console.error('upload-screenshot failed', err);
    return NextResponse.json({ error: 'Upload failed.' }, { status: 502 });
  }
}
